<script setup>
import {useSettingsStore, readOnlyProps} from "../../stores/settings";
import ComboCheckbox from "./ComboCheckbox.vue";
import {MODAL} from "../../use/constants";
import ComboSelect from "./ComboSelect.vue";
import ComboInput from "./ComboInput.vue";

const emit = defineEmits(['show-settings-modal'])

const settingsStore = useSettingsStore()
const settings = settingsStore.settings

const roomNameOptions = [
	{value: 0, label: t('appointments', 'Guest name + Date/Time')},
	{value: 1, label: t('appointments', 'Date/Time + Guest name')},
	{value: 2, label: t('appointments', 'Guest name only')},
]

const checkBbbEnabled = (evt) => {
	if (evt.propName === 'talk_enabled' && evt.value === true) {
		settings.bbbEnabled = false;
	}
}

const handleInterceptor = (data) => {

	if (settingsStore.k === true) {
		return false
	}

	let msg
	switch (data.propName) {
		case "talk_lobby":
			msg = t('appointments', "Automatically enable Talk lobby when an appointment is confirmed.")
			break
		case "talk_password":
			msg = t('appointments', "Automatically set Talk room pseudo random password when an appointment is confirmed.")
			break
		case "name":
			msg = t('appointments', "Customize Talk room name.")
			break
		case "talk_emailText":
			msg = t('appointments', "Customize Talk room URL email text.")
			break
		case "talk_formFieldEnable":
		case "talk_formLabel":
		case "talk_formPlaceholder":
		case "talk_formTxtReal":
		case "talk_formTxtVirtual":
			msg = t('appointments', 'Custom "Meeting type" form fields.')
			break
		default:
			msg = "Custom Feature"
	}

	emit('show-settings-modal', {
		type: MODAL.CONTRIBUTION,
		message: msg
	})
	return true
}

</script>

<template>
	<div class="ps-section-wrap">
		<ComboCheckbox
				prop-name="talk_enabled"
				:label="t('appointments', 'Create rooms for confirmed appointments')"
				@value-updated="checkBbbEnabled"
				:store="settingsStore"/>

		<div :class="{'sb_disable_nav-item':!settings.talk_enabled}">
			<ComboCheckbox
					prop-name="talk_delete"
					:disabled="!settings.talk_enabled"
					:label="t('appointments', 'Delete when appointments is removed')"
					:store="settingsStore"/>

			<ComboCheckbox
					prop-name="talk_lobby"
					:disabled="!settings.talk_enabled"
					:label="t('appointments', 'Enable lobby')"
					:click-interceptor="handleInterceptor"
					:store="settingsStore"/>

			<ComboCheckbox
					prop-name="talk_password"
					:disabled="!settings.talk_enabled"
					:label="t('appointments', 'Guest password')"
					:click-interceptor="handleInterceptor"
					:store="settingsStore">
				<template #help>When this option is selected, Talk rooms will be password-protected, and an autogenerated pseudo-random password will be sent to attendees along with a room/conversation link.</template>
			</ComboCheckbox>

			<ComboSelect
					prop-name="talk_nameFormat"
					:disabled="!settings.talk_enabled"
					:default-value="0"
					:placeholder="t('appointments', 'One option required')"
					:label="t('appointments', 'Talk room name')"
					:click-interceptor="handleInterceptor"
					:store="settingsStore"
					:options="roomNameOptions"/>

			<ComboInput
					type="textarea"
					prop-name="talk_emailText"
					:placeholder="t('appointments','Chat/Call link:')+' https://my_domain.com/index.php/call/to6d6y4e'"
					:disabled="!settings.talk_enabled"
					:label="t('appointments', 'Custom email text (optional)')"
					:focus-interceptor="handleInterceptor"
					:store="settingsStore">
				<template #help>
					{{
						t('appointments', 'You can override default email message. There are two tokens available, {token1} and if you use password protection {token2}, they will be replaced with the rooms URL and the password if used. Example:', {
							token1: '\{\{url\}\}',
							token2: "\{\{pass\}\}"
						})
					}}
					<code v-pre class="srgdev-appt-hs-code">Please use this link {{url}} to contact me.
						Your password is: {{pass}}
					</code>
				</template>
			</ComboInput>

			<ComboCheckbox
					class="ps-vert-spacing"
					prop-name="talk_formFieldEnable"
					:disabled="!settings.talk_enabled"
					:label="t('appointments', 'Add \'Meeting Type\' form field')"
					:click-interceptor="handleInterceptor"
					:store="settingsStore">
				<template #help>
					{{ t('appointments', 'When this option is enabled, a "select" drop-down will be added to the form with a choice of "In-person" or "Online (audio/video)". If a visitor selects an "In-person" meeting, a Talk room for this appointment will NOT be created.') }}
				</template>
			</ComboCheckbox>

			<div v-if="settings.talk_enabled && settings.talk_formFieldEnable"
					 class="ps-vert-spacing srgdev-appt-sb-indent"
					 style="padding-bottom: .5em">
				<ComboInput
						prop-name="talk_formLabel"
						:label="t('appointments', 'Custom label text (optional)')"
						:placeholder="readOnlyProps.talk_formDefLabel"
						:focus-interceptor="handleInterceptor"
						:store="settingsStore"/>
				<ComboInput
						prop-name="talk_formPlaceholder"
						:label="t('appointments', 'Custom placeholder text (optional)')"
						:placeholder="readOnlyProps.talk_formDefPlaceholder"
						:focus-interceptor="handleInterceptor"
						:store="settingsStore"/>
				<ComboInput
						prop-name="talk_formTxtReal"
						:label="t('appointments', 'Custom \'In-person\' option text (optional)')"
						:placeholder="readOnlyProps.talk_formDefReal"
						:focus-interceptor="handleInterceptor"
						:store="settingsStore"/>
				<ComboInput
						prop-name="talk_formTxtVirtual"
						:label="t('appointments', 'Custom \'Online\' option text (optional)')"
						:placeholder="readOnlyProps.talk_formDefVirtual"
						:focus-interceptor="handleInterceptor"
						:store="settingsStore"/>
				<ComboInput
						type="textarea"
						prop-name="talk_formTxtTypeChange"
						:label="t('appointments', 'Custom type change email text (optional)')"
						:focus-interceptor="handleInterceptor"
						:store="settingsStore">
					<template #help>
						{{
							t('appointments', 'If this field is not empty and has two tokens {token1} (can contain any text) and {token2} (MUST be new_type), then this text will be attached to the email and attendees will be able to switch their meeting type simply by clicking the link {token}. Example:', {
								token1: '\{\{link_text\}\}',
								token2: "\{\{new_type\}\}"
							})
						}}
						<code v-pre class="srgdev-appt-hs-code">Click {{here}} to change your appointment type to {{new_type}}.
						</code>
						{{ t('appointments', 'Talk rooms will be created and deleted automatically when a meeting type changes.') }}
					</template>
				</ComboInput>
			</div>
		</div>
	</div>
</template>

<style scoped>

</style>