<script setup>
import {useSettingsStore} from "../../stores/settings";
import ComboCheckbox from "./ComboCheckbox.vue";

const settingsStore = useSettingsStore()
const settings = settingsStore.settings

const checkTalkEnabled = (evt) => {
	if (evt.propName === 'bbbEnabled' && evt.value === true) {
		settings.talk_enabled = false;
	}
}

</script>

<template>
	<div class="ps-section-wrap">
		<ComboCheckbox
				prop-name="bbbEnabled"
				:label="t('appointments', 'Create video rooms for confirmed appointments')"
				@value-updated="checkTalkEnabled"
				:store="settingsStore"/>
		<div :class="{'sb_disable_nav-item':!settings.bbbEnabled}">
			<ComboCheckbox
					prop-name="bbbDelete"
					:disabled="!settings.bbbEnabled"
					:label="t('appointments', 'Delete when appointments is removed')"
					:store="settingsStore"/>
<!--			<ComboCheckbox-->
<!--					prop-name="bbbAutoDelete"-->
<!--					:disabled="!settings.bbbEnabled"-->
<!--					:label="t('appointments', 'Auto-delete 24 hours after the call is finished')"-->
<!--					:store="settingsStore"/>-->
			<ComboCheckbox
					prop-name="bbbPassword"
					:disabled="!settings.bbbEnabled"
					:label="t('appointments', 'Guest password')"
					:store="settingsStore">
				<template #help>When this option is selected, video rooms will be password-protected, and an autogenerated pseudo-random password will be sent to attendees along with the room link.</template>
			</ComboCheckbox>
			<ComboCheckbox
					class="ps-vert-spacing"
					prop-name="bbbFormEnabled"
					:disabled="!settings.bbbEnabled"
					:label="t('appointments', 'Add \'Meeting Type\' form field')"
					:store="settingsStore">
				<template #help>
					{{ t('appointments', 'When this option is enabled, a "select" drop-down will be added to the form with a choice of "In-person" or "Online (audio/video)". If a visitor selects an "In-person" meeting, a Talk room for this appointment will NOT be created.') }}
				</template>
			</ComboCheckbox>
		</div>
	</div>
</template>

<style scoped>

</style>